global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

    static_configs:
      - targets: ['demo-app:80']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
